services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: my_db
    ports:
      - 5432:5432

  localstack:
    container_name: "my_localstack_container"
    image: localstack/localstack
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSIST_ALL=false
